### PR TITLE
🐣

### PR DESCRIPTION
**Pull request by fatiherikli**
👀

### CODE REVIEW

**Comment by sdogruyol** [comment]
Vay refactor :+1:

**Comment by fatiherikli** [comment]
Yep. Coverages the %70 of codebase.

On Wednesday, 23 December 2015, Serdar Dogruyol <notifications@github.com>
wrote:

> Vay refactor [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sdogruyol/fast-http-server/pull/1#issuecomment-166890793>
> .
>


-- 
Fatih Erikli
http://www.fatiherikli.com

**Comment by sdogruyol** [comment]
Could you please update your commit message to something like "Refactor" ?

**Comment by fatiherikli** [comment]
No I can't.

On Wednesday, 23 December 2015, Serdar Dogruyol <notifications@github.com>
wrote:

> Could you please update your commit message to something like "Refactor" ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sdogruyol/fast-http-server/pull/1#issuecomment-166891074>
> .
>


-- 
Fatih Erikli
http://www.fatiherikli.com

**Comment by sdogruyol** [comment]
If you want you can open another PR with a proper message. Thanks :+1:

**Comment by fatiherikli** [comment]
#2

**Pull request closed without merging**
